-- H2 2.3.232; 
;              
CREATE USER IF NOT EXISTS "SA" SALT '64e27553835e85b8' HASH '7cdb1a44053ec47467b218d2b7db5d02340d14d783d164e0ad27e7c06c8c4ba0' ADMIN;          
CREATE SEQUENCE "PUBLIC"."ACCOUNT_SEQ" AS NUMERIC(19, 0) START WITH 1 RESTART WITH 101 INCREMENT BY 50;        
CREATE SEQUENCE "PUBLIC"."AUDIT_LOG_SEQ" AS NUMERIC(19, 0) START WITH 1 INCREMENT BY 50;       
CREATE SEQUENCE "PUBLIC"."CUSTOMER_SEQ" AS NUMERIC(19, 0) START WITH 1 RESTART WITH 101 INCREMENT BY 50;       
CREATE SEQUENCE "PUBLIC"."TRANSACTION_SEQ" AS NUMERIC(19, 0) START WITH 1 RESTART WITH 151 INCREMENT BY 50;    
CREATE GLOBAL TEMPORARY TABLE "PUBLIC"."HTE_AUDIT_LOG"(
    "RN_" INTEGER NOT NULL,
    "ID" BIGINT,
    "ACTION" CHARACTER VARYING(255),
    "AUDIT_DETAILS" CHARACTER VARYING(255),
    "SOURCE" CHARACTER VARYING(255),
    "TIMESTAMP" CHARACTER VARYING(255)
);           
ALTER TABLE "PUBLIC"."HTE_AUDIT_LOG" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1" PRIMARY KEY("RN_");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.HTE_AUDIT_LOG;            
CREATE GLOBAL TEMPORARY TABLE "PUBLIC"."HTE_ACCOUNT"(
    "BALANCE" FLOAT(24),
    "RN_" INTEGER NOT NULL,
    "ID" BIGINT,
    "ACCOUNT_NUMBER" CHARACTER VARYING(255),
    "ACCOUNT_TYPE" CHARACTER VARYING(255),
    "CUSTOMERID" CHARACTER VARYING(255),
    "DATE_OPENED" CHARACTER VARYING(255),
    "STATUS" CHARACTER VARYING(255)
);  
ALTER TABLE "PUBLIC"."HTE_ACCOUNT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_7" PRIMARY KEY("RN_");  
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.HTE_ACCOUNT;              
CREATE GLOBAL TEMPORARY TABLE "PUBLIC"."HTE_TRANSACTION"(
    "AMOUNT" FLOAT(24),
    "RN_" INTEGER NOT NULL,
    "ID" BIGINT,
    "ACCOUNT" CHARACTER VARYING(255),
    "DATE_TRANSACTED" CHARACTER VARYING(255),
    "STATUS" CHARACTER VARYING(255),
    "TRANSACTION_TYPE" CHARACTER VARYING(255)
);       
ALTER TABLE "PUBLIC"."HTE_TRANSACTION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8" PRIMARY KEY("RN_");              
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.HTE_TRANSACTION;          
CREATE GLOBAL TEMPORARY TABLE "PUBLIC"."HTE_CUSTOMER"(
    "RN_" INTEGER NOT NULL,
    "ID" BIGINT,
    "DATE_REGISTERED" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(255),
    "PHONE_NUMBER" CHARACTER VARYING(255),
    "STATUS" CHARACTER VARYING(255)
);         
ALTER TABLE "PUBLIC"."HTE_CUSTOMER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3" PRIMARY KEY("RN_"); 
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.HTE_CUSTOMER;             
CREATE MEMORY TABLE "PUBLIC"."ACCOUNT"(
    "ID" BIGINT NOT NULL,
    "ACCOUNT_NUMBER" CHARACTER VARYING(255),
    "ACCOUNT_TYPE" CHARACTER VARYING(255),
    "BALANCE" FLOAT(24),
    "CUSTOMERID" CHARACTER VARYING(255),
    "DATE_OPENED" CHARACTER VARYING(255),
    "STATUS" CHARACTER VARYING(255)
);   
ALTER TABLE "PUBLIC"."ACCOUNT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_E" PRIMARY KEY("ID");       
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.ACCOUNT;  
INSERT INTO "PUBLIC"."ACCOUNT" VALUES
(1, 'AC00001', 'Savings', 50000.3, '1', '04-Sep-2024', 'Active'),
(51, 'AC00002', 'Savings', 60000.3, '2', '05-Sep-2024', 'Active');     
CREATE MEMORY TABLE "PUBLIC"."AUDIT_LOG"(
    "ID" BIGINT NOT NULL,
    "ACTION" CHARACTER VARYING(255),
    "AUDIT_DETAILS" CHARACTER VARYING(255),
    "SOURCE" CHARACTER VARYING(255),
    "TIMESTAMP" CHARACTER VARYING(255)
);            
ALTER TABLE "PUBLIC"."AUDIT_LOG" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_B" PRIMARY KEY("ID");     
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.AUDIT_LOG;
CREATE MEMORY TABLE "PUBLIC"."CUSTOMER"(
    "ID" BIGINT NOT NULL,
    "DATE_REGISTERED" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(255),
    "PHONE_NUMBER" CHARACTER VARYING(255),
    "STATUS" CHARACTER VARYING(255)
);          
ALTER TABLE "PUBLIC"."CUSTOMER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_5" PRIMARY KEY("ID");      
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.CUSTOMER; 
INSERT INTO "PUBLIC"."CUSTOMER" VALUES
(1, '04-Oct-2024', 'Vimal Kumar', '+919922334466', 'Active'),
(2, '03-Oct-2024', 'Abhishek Kumar', '+919922334444', 'Active');          
CREATE MEMORY TABLE "PUBLIC"."TRANSACTION"(
    "ID" BIGINT NOT NULL,
    "ACCOUNT" CHARACTER VARYING(255),
    "AMOUNT" FLOAT(24),
    "DATE_TRANSACTED" CHARACTER VARYING(255),
    "STATUS" CHARACTER VARYING(255),
    "TRANSACTION_TYPE" CHARACTER VARYING(255)
);        
ALTER TABLE "PUBLIC"."TRANSACTION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_F" PRIMARY KEY("ID");   
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.TRANSACTION;              
INSERT INTO "PUBLIC"."TRANSACTION" VALUES
(1, 'AC00001', 500.0, '06-Oct-2024', 'Success', 'Debit'),
(51, 'AC00001', 1500.0, '07-Oct-2024', 'Success', 'Credit'),
(101, 'AC00002', 200.0, '07-Oct-2024', 'Success', 'Credit');  
